### ISSUE TITLE
missing lambda.zip file?

### ISSUE THREAD

**Issue by declanfleming** [christian-fei/timelapse-lambda#1]
Hi - thanks for creating this!  I'm new to lambda and may be missing something simple, but when I run create-aws-lambda I get the error:

Error parsing parameter '--zip-file': Unable to load paramfile fileb://lambda.zip: [Errno 2] No such file or directory: 'lambda.zip'

This is probably basic and due to my inexperience.  Thanks!
Declan

**Comment by declanfleming** [comment]
Ah, found the "make-aws-lambda-zip" script.

**Comment by christian-fei** [comment]
hello!

thanks for the interest, and great that you resolved the issue.

please let me know how the setup process goes, and if you have any suggestion, PRs are very welcome!
